### ISSUE TITLE
Got `StackOverflowError` while evaluating `htm.java` with K =1

### ISSUE THREAD

**Issue by saledouble** [ponder-lab/Optimize-Java-8-Streams-Refactoring#200]
When the K = 1, there is a exception.
```
java.lang.StackOverflowError
	at edu.cuny.hunter.streamrefactoring.core.analysis.StreamStateMachine$$Lambda$485/1470607708.<init>(Unknown Source)
	at edu.cuny.hunter.streamrefactoring.core.analysis.StreamStateMachine$$Lambda$485/1470607708.get$Lambda(Unknown Source)
	at edu.cuny.hunter.streamrefactoring.core.analysis.StreamStateMachine.computePossibleOriginStreams(StreamStateMachine.java:534)
	at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
```

Found this issue from https://github.com/ponder-lab/Stream-Performance-Refactoring-Paper/issues/29

**Comment by khatchad** [comment]
Please detail the steps to reproduce.
